### ISSUE TITLE
Instructions to deploy your own gallery

### ISSUE THREAD

**Issue by jtpio** [voila-gallery/gallery#18]
It would be great to add instructions in the `README.md` to deploy your own TLJH with the voila gallery.

For TLJH it could point to https://the-littlest-jupyterhub.readthedocs.io.
And for the gallery the extra steps to get it installed.

**Comment by yuvipanda** [comment]
https://github.com/voila-gallery/gallery/issues/10 has some right now

**Comment by jtpio** [comment]
Nice. Ideally we can end up with something like this to automatically provision the machines on DO / OVH and so on:

```bash
curl https://raw.githubusercontent.com/jupyterhub/the-littlest-jupyterhub/master/bootstrap/bootstrap.py \
 | sudo python3 - \
   --plugin git+https://github.com/voila-gallery/gallery \
   --admin voila
```

**Comment by yuvipanda** [comment]
@jtpio yeah, I think once #10 is closed (post-install systemd unit) we can use the command you just wrote here.

**Comment by jtpio** [comment]
There will also be the question on how to build / rebuild the docker images.

**Comment by jtpio** [comment]
Right that's the last item!

**Comment by yuvipanda** [comment]
I'd say the way to do it is to write a small script that does the following:

1. Git pull the repo to get newest gallery.yaml
2. Run the build images script
3. Sleep for some time, and redo

We can then put this script in a systemd unit (I like doing that over putting it in a timer).

We should also add some logic to the JupyterHub service to only show gallery items that have an existing image. This prevents us from showing gallery items that will fail to launch since their images haven't been built yet.

**Comment by jtpio** [comment]
>     1. Git pull the repo to get newest gallery.yaml

Maybe we could just fetch the `gallery.yaml` file instead, since it's the only file the `build_images.py` script needs to build new Docker images?
