### ISSUE TITLE
There is no easy way to go back to the home page

### ISSUE THREAD

**Issue by pbugnion** [voila-gallery/gallery#3]
Once the user is viewing an example, the only way for them to go back to the landing page and view another example is to hit `/hub/logout`.

**Comment by pbugnion** [comment]
@yuvipanda mentioned this might be solved with named servers?

**Comment by yuvipanda** [comment]
There are two issues here:

1. Hitting 'back' in the browser should let useres go back to the home page
2. A way to visually provide 'back' on the page for each dashboard.

Named servers would definitley help with (1) - I'll play with it sometime this week. I don't know what to do about (2) though, since voila templates are arbitrary.
