### ISSUE TITLE
500 error with codex-clustergrammer2 dashbaord

### ISSUE THREAD

**Issue by cornhundred** [voila-gallery/gallery#63]
@jtpio I'm seeing a 500 Internal server error when I try to run the codex-clustergrammer2 example from https://voila-gallery.org/services/gallery/

The console shows the following error:

<img width="622" alt="Screen Shot 2019-08-05 at 10 48 14 AM" src="https://user-images.githubusercontent.com/8352840/62473441-be63ae00-b76e-11e9-89ec-1cb13a4fe3ba.png">

**Comment by jtpio** [comment]
Thanks for the report.

It seems to be related to `voila` being installed with `pip` (see #54 for reference).

I opened https://github.com/ismms-himc/codex_dashboard/pull/4 to update voila to the latest version (which includes the fix).

**Comment by cornhundred** [comment]
Thanks for the fix. I merged https://github.com/ismms-himc/codex_dashboard/pull/4, do I need to do anything else to fix the dashboard?

**Comment by jtpio** [comment]
Since that corresponds to a new version of the example, we need to update the [`ref` field in `gallery.yaml`](https://github.com/voila-gallery/gallery/blob/f178eaa2c0e98fe4b64feaa7734813d5d529f451/tljh-voila-gallery/tljh_voila_gallery/gallery.yaml#L48) to the new commit hash: [b8c8fb820c918d4fc343cf6d8a25bd81cad837c9](https://github.com/ismms-himc/codex_dashboard/commit/b8c8fb820c918d4fc343cf6d8a25bd81cad837c9)

Would you like to open a PR?

**Comment by cornhundred** [comment]
@jtpio I made a pull request, feel free to edit if something was done incorrectly https://github.com/voila-gallery/gallery/pull/64

**Comment by jtpio** [comment]
Thanks @cornhundred.

Fixed by https://github.com/ismms-himc/codex_dashboard/pull/4 and https://github.com/voila-gallery/gallery/pull/64.
